### ISSUE TITLE
Build fails when packaging configuration element(s) with array or composite type values

### ISSUE THREAD

**Issue by idodekov** [vmware/vrealize-developer-tools#93]
### Description

An error is received when trying to package a configuration element with array or composite type values and build fails. Issue is not reproducible on vRBT version 2.4.5.

### Steps to Reproduce

1. Create configuration element with the following content:

<?xml version='1.0' encoding='UTF-8'?>
<config-element id="095a32a8-9972-46c8-b580-16371bc52b16" version="0.0.1">
  <display-name><![CDATA[Configuration]]></display-name>
  <atts>
    <att name="validBackupSchedules" type="Array/string" read-only="false">
      <value encoded="n"><![CDATA[[11:string#1700,11:string#1800,11:string#1900,11:string#2000,11:string#2100,11:string#2200,11:string#2300,11:string#0000,11:string#0100,11:string#0200,11:string#0300,11:string#0400,11:string#0500,11:string#0600,15:string#NOBACKUP,]]]></value>
      <description><![CDATA[Valid Backup Window in HHMM]]></description>
    </att>
  </atts>
</config-element>

2. Try to execute mvn package

**Expected behavior:** Build fails if array or composite type value is present in configuration element

**Actual behavior:** Build should succeed.

**Reproduces how often:** Whenever an array/composite type value is present

#### Client

-   vRealize Developer Tools Version: N/A
-   vRealize Build Tools Version: 2.10
-   Visual Studio Code Version: N/A
-   OS Version: N/A

#### Server

-   vRealize Automation Version: 7.6
-   vRealize Orchestrator Version: 7.6

### Failure Logs

mvn release:prepare --batch-mode --settings "settings.xml" -DreleaseVersion=1.0.3 -Dresume=false -DpushChanges=false
[ERROR] Failed to execute goal com.vmware.pscoe.maven.plugins:o11n-xml-package-maven-plugin:2.10.0:package (default-package) on project cba-toolchain-vro.workflows: Could not write package to disk. Error found while serializing object. cannot convert value of validBackupSchedules to decrypt it: Array value has invalid format -> [Help 1]

**Comment by carlosaya** [comment]
@idodekov we are having this issue as well. I noticed that exporting the config element from the vro 7.6 gui and REST API also yields strange formatting vs past versions of vro. Is the problem with build tools not supporting the new format or is there a bug in vro when exporting these types of config elements?

**Comment by idodekov** [comment]
@carlosaya we're currently confirming what's the root cause. Looks like a bug in vRBT as it's not reproducible when using an older version (2.4.5). Stay tuned.

**Comment by BenCamareno** [comment]
@idodekov exporting a config element with array or composite type values with both vRBT versions 2.4.5 and 2.10.0 on vRO 7.6 adds extra characters at the start of the attribute value type. The maven build doesn't fail on 2.4.5, but the contents of the config elements are not correct.

**Comment by mitevam** [comment]
This is a problem with the format of the API response produced by some 7.5 and 7.6 builds of vRO. The format the vRO REST API uses when exporting values of configuration elements attributes of type Array/Composite type is slightly modified, which causes the subsequent packaging and importing of those configuration elements to fail. 

As a workaround we suggest to :
- Upgrade to the latest version of vRO 7.6 , or
- Use an installer workflow to set the values of configuration elements instead of importing them

As we have two workaround available I am closing the issue.

**Comment by carlosaya** [comment]
We are on a very recent release (as of November 2020) of 7.6 and still have this issue. Please provide a known working build number.

**Comment by BenCamareno** [comment]
@mitevam You haven't provided a link to the latest build or even what the build number is.

**Comment by idodekov** [comment]
@BenCamareno @carlosaya Could you guys try in a staging environment with latest build from here: https://kb.vmware.com/s/article/70629 . We're also waiting for the confirmation from VMware R&D about the build number where this is addressed.
Please note that you'll also need to export all configuration elements before you try to import them again.

**Comment by BenCamareno** [comment]
@mitevam @idodekov after applying this patch to our vRO dev env nothing has changed. We're still getting this issue. 
Please re-open this since it has not been solved.
Thanks,
Ben
